<?php
/**
 * Kapitchi Zend Framework 2 Modules
 *
 * @copyright Copyright (c) 2012-2014 Kapitchi Open Source Community (http://kapitchi.com/open-source)
 * @license   http://opensource.org/licenses/MIT MIT
 */ 
?>
<table>
    <tr>
        <td><?=$this->translate("Name")?></td>
        <td><?=$this->name?></td>
    </tr>
    <tr>
        <td><?=$this->translate("Email")?></td>
        <td><?=$this->email?></td>
    </tr>
    <tr>
        <td><?=$this->translate("Service")?></td>
        <td><?=$this->service?></td>
    </tr>
    <tr>
        <td><?=$this->translate("Date")?></td>
        <td><?=$this->when?></td>
    </tr>
    <tr>
        <td><?=$this->translate("Note")?></td>
        <td><?=$this->note?></td>
    </tr>
</table>