<?php
$this->headLink()->prependStylesheet($this->basePath() . '/vendor/ng-tags-input/ng-tags-input.min.css');
//$this->headLink()->prependStylesheet($this->basePath() . '/vendor/ng-tags-input/ng-tags-input.bootstrap.min.css');
$this->headLink()->prependStylesheet('//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css');
$this->headLink()->prependStylesheet('//cdnjs.cloudflare.com/ajax/libs/textAngular/1.2.3/textAngular.min.css');

$this->ng('ng-app', 'MyApp');
?>
<div id="ng-app" ng-class="{'app-mode-edit': app.edit}">
    <ui-view></ui-view>
</div>