<?php
$this->ng('ng-app', 'LoginApp');
?>
<div id="ng-app" ng-controller="FbLoginController" class="container">
    <div ng-show="authResult.code == 1" class="row">
        <h1>Hi {{authResult.userProfile.displayName}}!</h1>
        <img ng-src="{{authResult.userProfile.imageUrl}}" class="img-responsive">
        <a href="/" target="_self" class="btn btn-primary">Go to homepage</a>
    </div>

    <button ng-show="showLogin" ng-click="login()" class="btn btn-primary">Login</button>
    <button ng-show="authResult.code == 1" ng-click="logout()" class="btn btn-primary">Logout</button>
</div>