<?php
$this->ng('login-app');

$url = $this->authenticationAdapterManager()->getCallbackUrl('facebook_javascript', [
    'response_type' => 'token',
    'client_id' => 'jsclient',
    'redirect_uri' => '/login',
    'state' => '123'
]);

$this->ng()->constant('fbAuthUrl', $url);
?>

<div ng-controller="FbLoginController" class="ng-cloak">
    <button ng-show="showLogin" ng-click="login()" class="btn btn-primary">Connect with Facebook</button>
</div>
