<?php
$this->ng('login-app');

$url = $this->authenticationAdapterManager()->getCallbackUrl('facebook_javascript', [
    'response_type' => 'token',
    'client_id' => 'jsclient',
    'redirect_uri' => '/oauthcallback',
    'state' => '123'
]);

$this->ng()->constant('fbAuthUrl', $url);

?>

<oauth
    site="<?=$this->escapeHtmlAttr($this->serverUrl())?>"
    client-id="jsclient"
    redirect-uri="<?=$this->escapeHtmlAttr($this->serverUrl('/login'))?>"
    response-type="token"
    scope=""
    state="123"
    template="/template/login-button.html">
    
</oauth>
