<h1>{{album.title}}</h1>
<?php if($this->identity()):?><button ng-click="createItem()">Create item</button><?php endif?>
<div <?php if($this->identity()):?>ui-tree="treeOptions" data-empty-place-holder-enabled="false" ui-tree-nodes ng-model="albumItemRelCollection.items"<?php endif?> class="row">

    <div ng-repeat="itemRel in albumItemRelCollection.items" <?php if($this->identity()):?>ui-tree-node<?php endif?> class="col-lg-3 col-md-4 col-xs-6 thumb">
        <div class="thumbnail">
            <img ng-click="fullScreenGalleryRel(itemRel, albumItemRelCollection)" ng-src="{{itemRel._embedded.album_item._embedded.thumbnail_file._links.thumbnail_default.href}}" class="img-responsive">
            <div class="caption">
                <h3><a <?php if($this->identity()):?>ng-click="albumItemUpdate(itemRel._embedded.album_item)"<?php endif?>>{{itemRel._embedded.album_item.title}}</a></h3>
                <?php if($this->identity()):?>
                    <a ui-tree-handle class="btn btn-default" role="button"><i class="glyphicon glyphicon-sort" ></i></a>
                    <a ng-click="createItemAfter(itemRel)" class="btn btn-default" role="button">Create after</a>
                    <a ng-click="albumItemRelRemove(albumItemRelCollection, itemRel)" class="btn btn-default" role="button">Remove</a>
                <?php endif?>
            </div>
        </div>
    </div>

</div>